[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "pyezvizapi"
description = "EZVIZ API client for Home Assistant and CLI"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version"]

[tool.ruff]
line-length = 100
target-version = "py312"
src = ["pyezvizapi"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","SIM","PL","RUF","SLF"]
ignore = ["E501"] # long URLs ok

# Per-file tuning
[tool.ruff.lint.per-file-ignores]
# CLI files are naturally branchy/return-heavy; quiet those here:
"pyezvizapi/__main__.py" = ["PLR0911","PLR0912","PLR0915"]
# Re-export noise in __init__ (if applicable):
"pyezvizapi/__init__.py" = ["F401"]

# Import sorting to match HA expectations
[tool.ruff.lint.isort]
known-first-party = ["pyezvizapi"]
known-third-party = ["homeassistant", "aiohttp", "voluptuous", "yarl", "pandas", "xmltodict", "Crypto"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
force-sort-within-sections = true

# Pylint-like thresholds (only if you prefer global relaxation instead of per-file ignores)
[tool.ruff.lint.pylint]
allow-magic-value-types = ["int", "str"]
max-args = 10

[tool.mypy]
python_version = "3.12"
files = ["pyezvizapi"]
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_no_return = true
no_implicit_optional = true
check_untyped_defs = true

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "types-requests"]

[tool.coverage.run]
source = ["pyezvizapi"]