name: CI
on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install -U pip wheel

      - name: Install project + dev deps
        run: pip install -e .[dev]

      - name: Ruff
        run: ruff check .

      - name: mypy
        run: mypy .

      - name: pytest
        run: pytest -q